### PR TITLE
Enable Wisconsin Fetching/Loading

### PR DESCRIPTION
**Pull request by nbdavies**
* Filled out `office` and `party` fixtures. Office may still need circuit court and district attorney.
* Filled in datasource.py and load.py based on comparable states' logic.

### CODE REVIEW

**Comment by nbdavies** [comment]
Also, I don't have a great understanding about how the whole thing is supposed to work, so PR comments would be appreciated. Especially if anything looks strange, anything in particular I ought to add in this PR, or what the next steps from here should be.

**Comment by dwillis** [comment]
@nbdavies Sorry I haven't been able to take a look at this - and it might be a few more days before I can - but will do so ASAP.

**Comment by nbdavies** [comment]
Hi @dwillis,
I managed to get the Fetch and Load steps working for Wisconsin, with everything in this PR. Could you review/possibly merge?
Thanks!

**Comment by dwillis** [comment]
@nbdavies thanks!

**Pull request merged**
