### PR TITLE
First version for the datasource integration of Vermont.

### PR DESCRIPTION
**Pull request by jslap**
First version for the datasource integration of Vermont.
- missing offices: state attorney, sec of state and sate house

Note:
It is my first pull-request in your project, but I would like to continue working on this. Please tell me how I can improve on complying with your project standards (guidelines, tests...).

### CODE REVIEW

**Comment by dwillis** [comment]
Hi @jslap, thanks for this! I'll be reviewing it this week, but a couple of initial thoughts:

* for filenames, the format is this (using 2014 general results for state house as an example): `20141104__vt__general__state_house__precinct.csv`, so the office comes before the reporting level. If it's both houses of the state legislature you can use `state_legislative` as the office, but `precinct` always comes last.
* The `name` attribute in the datasource.mapping elements is political jurisdiction, not the office. So, for all state legislative offices it would be 'Vermont' and for a particular county it would be the county name.

**Comment by jslap** [comment]
Thanks Derek, I'll work on this.

**Comment by dwillis** [comment]
Thanks! Similarly, the `ocd_id` would be 'ocd-division/country:us/state:vt' for statewide results and 'ocd-division/country:us/state:vt/county:[county_name]' for county results. Oh, and it's 'precinct' :-)

**Comment by jslap** [comment]
Hello,
I fixed for the latest comment. Tell me if there is some other stuff to fix.

**Comment by dwillis** [comment]
The only other thing I see is that the `generated_filename` attribute isn't quite right. Instead of `20140826__vt__republican__primary__state_ltgov.csv`, the format should be `20140826__vt__republican__primary__lieutenant_governor.csv`. Same with `governor` instead of `state_gov`.

**Comment by jslap** [comment]
Hi Derek,
I'm currently continuing the dev on the vt data. And by doing this, I happened to do some refactor on the datasource class.  Those issues will be fixed in it, but also a lot of other stuff. It is not finalize yet, but I did the datasource, load, transform and some validation... 
Should I update this pull request with my new dev, or replace it with a new one?
Also, Processing the data takes a lot of time and CPU power, Do you guys have access to some more powerful cloud instances, or you just wait the night until the processing is done? Or maybe I just need to optimize my code...

**Comment by dwillis** [comment]
I'd say just update this pull request. And loading the data definitely can use a lot of time and CPU energy, but it shouldn't take hours, particularly for a small state like Vermont. Statewide precinct files from Florida load in about 5 minutes or less.

**Comment by jslap** [comment]
OK. I just commited my latest change into this pull request.
I'm ready to hear your comments about it, and make some corrections...

**Comment by dwillis** [comment]
Hi @jslap - I'm traveling for the next week and don't have good Internet access, but will check asap.

**Comment by dwillis** [comment]
Sorry to be so late in getting to this, but it looks good and i'll have some further comments shortly.

**Comment by dwillis** [comment]
Ok, some further comments:

It would be great if, instead of doing a datasource entry for each political jurisdiction, you combined them into one for a single election, since that's the preferred output. What I mean by that is that even if you'll need to pull multiple source files, having a single output file would be great. Right now the 2016 datasource.mappings command outputs 1006 results, seemingly one for each office and party (for primaries). You might want to check out another state, like Virginia, and run the datasource.mappings command for that to get a better idea of what I'm talking about.

**Comment by jslap** [comment]
Sorry for the delay (3 years! Realy sorry.)
I'm having some time again to work on this. I understand what you want, I agree that the number of datasource is not convenient at all. I see what is the result that we want.
But I don't know how to achieve this with the current structure: It seems that one datasource entry can only map one url and one local file. 
I'm surely missing something here, if you have any clue on how to do this, it would be great.

**Pull request merged**
